version: 0.2

phases:
   install:
      runtime-versions:
         java: openjdk8         
   build:
      commands:
         - echo "Build initiated"
         - mvn clean package
   artifacts:
      files:
         - target/**/*
      discard-paths: yes
      
         